### ISSUE TITLE
variable problem in your code

### ISSUE THREAD

**Issue by mrjumpy** [xbpf/which-gtin#6]
Highly recommend that you should change `let` in your code to `var`  (line81, index.js)
because you don't compile your code, in some browser, like firefox
`let` will cause some error.

especially for react / webpack development, in common, we don't compile our node_modules.

**Comment by SEAPUNK** [comment]
A pull request is generally welcome and preferred for issues like these.

Either way, I just now published 1.0.1. https://github.com/xbpf/which-gtin/commit/411622481a3198cb3c4997cd16329c0cf6d4ff91
